APIS-6721 Upgrade mongo lib to 1.7.0
hmrc/api-platform-jobs pull request #70
Opened 2024-01-24 14:00 UTC by petekirby-ee

2024-01-29 12:02 UTC, AndySpaven requested changes
So lots of stuff that could move to ClockNow/FixedClock and the syntaxes that JG added to common lib.

2024-01-29 12:02 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatform/modules/common/services/InstantSyntax.scala
> +/*
It should be the one in the lib now (common domain - might mean approving/fixing John's PR) so this doesn't proliferate

2024-01-29 12:02 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/DeleteUnverifiedDevelopersJob.scala
> +      developerDetails <- developerConnector.fetchUnverifiedDevelopers(instant().minus(createdBeforeInDays, ChronoUnit.DAYS), jobConfig.limit)
maybe use Duration.ofDays(createdBeforeInDays) - not sure that this is the "new" standard form

2024-01-29 12:02 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/TimedJob.scala
> +    val nextInstanceOfTime     = if (timeToday.isBefore(currentDateTime)) timeToday.plus(1, ChronoUnit.DAYS) else timeToday
Ditto

2024-01-29 12:02 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/UpdateUnusedApplicationRecordsJob.scala
> +    Instant
Transform this to instant() and use ClockNow maybe to ensure truncation.

2024-01-29 12:02 UTC, AndySpaven commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/UpdateUnusedApplicationRecordsJob.scala
> +    val lastInteractionDate               = LocalDate.ofInstant(applicationUsageDetails.lastAccessDate.getOrElse(applicationUsageDetails.creationDate), ZoneOffset.UTC)
Could use the common lib syntaxes to go asLocalDateTime or asInstant

2024-01-29 12:02 UTC, AndySpaven commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +  val timestamp    = Instant.now()
Time to bring in fixedclock maybe ?

2024-01-29 12:02 UTC, AndySpaven commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +      val timestamp             = LocalDateTime.of(2020, 1, 1, 12, 0, 0).toInstant(ZoneOffset.UTC)
using syntax..

2024-01-29 12:02 UTC, AndySpaven commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +      val timestamp             = LocalDateTime.of(2020, 1, 1, 12, 0, 0).toInstant(ZoneOffset.UTC)
using syntax..

2024-01-29 12:02 UTC, AndySpaven commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ThirdPartyApplicationConnectorSpec.scala
> +      val lastUseDate        = lastUseLDT.toInstant(ZoneOffset.UTC)
using syntax.. Could just become `now.minusMonths(12).asInstant()`

2024-01-29 15:05 UTC, petekirby-ee commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/DeleteUnverifiedDevelopersJob.scala
> +      developerDetails <- developerConnector.fetchUnverifiedDevelopers(instant().minus(createdBeforeInDays, ChronoUnit.DAYS), jobConfig.limit)
Fixed

2024-01-29 15:05 UTC, petekirby-ee commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/TimedJob.scala
> +    val nextInstanceOfTime     = if (timeToday.isBefore(currentDateTime)) timeToday.plus(1, ChronoUnit.DAYS) else timeToday
Fixed

2024-01-29 15:16 UTC, petekirby-ee commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ThirdPartyApplicationConnectorSpec.scala
> +      val lastUseDate        = lastUseLDT.toInstant(ZoneOffset.UTC)
Fixed

2024-01-29 15:16 UTC, petekirby-ee commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +  val timestamp    = Instant.now()
Done

2024-01-29 15:17 UTC, petekirby-ee commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/UpdateUnusedApplicationRecordsJob.scala
> +    Instant
Done

2024-01-30 13:50 UTC, petekirby-ee commented on app/uk/gov/hmrc/apiplatformjobs/scheduled/UpdateUnusedApplicationRecordsJob.scala
> +    val lastInteractionDate               = LocalDate.ofInstant(applicationUsageDetails.lastAccessDate.getOrElse(applicationUsageDetails.creationDate), ZoneOffset.UTC)
Done

2024-01-30 13:51 UTC, petekirby-ee commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +      val timestamp             = LocalDateTime.of(2020, 1, 1, 12, 0, 0).toInstant(ZoneOffset.UTC)
Done

2024-01-30 13:51 UTC, petekirby-ee commented on test/uk/gov/hmrc/apiplatformjobs/connectors/ApplicationCommandConnectorSpec.scala
> +      val timestamp             = LocalDateTime.of(2020, 1, 1, 12, 0, 0).toInstant(ZoneOffset.UTC)
Done

2024-01-30 13:51 UTC, petekirby-ee commented on app/uk/gov/hmrc/apiplatform/modules/common/services/InstantSyntax.scala
> +/*
Done

2024-01-30 15:22 UTC, AndySpaven approved these changes

2024-01-30 15:47 UTC, merged